# Generated by Django 2.2 on 2019-06-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('subject', models.CharField(default='', max_length=255)),
                ('time', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakeLaterExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_later_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('choice_e', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('0', 'choice_a'), ('1', 'choice_b'), ('2', 'choice_c'), ('3', 'choice_d'), ('4', 'choice_e')], max_length=3)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='exams.Exam')),
            ],
            options={
                'verbose_name': 'MCQ',
                'verbose_name_plural': 'MCQs',
            },
        ),
        migrations.CreateModel(
            name='FinishedExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField()),
                ('full_mark', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_url', to='exams.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
