# Generated by Django 2.2 on 2019-06-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
