# Generated by Django 2.2 on 2019-06-30 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_auto_20190626_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('career', models.CharField(blank=True, max_length=255)),
                ('birth_dat', models.DateField(blank=True, null=True)),
                ('is_teacher', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('avatar', models.ImageField(upload_to='personal/%y/%m/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
