# Generated by Django 2.2 on 2019-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190630_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://zcoin.io/wp-content/uploads/2017/01/blank-avatar-e1484377033610.png', upload_to='personal/%y/%m/'),
        ),
    ]
