# Generated by Django 2.2 on 2019-07-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20190630_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/elshafeay/emt7ank/blank_avatar.png', upload_to='personal/%y/%m/'),
        ),
    ]
