# Generated by Django 2.2.3 on 2019-07-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20190705_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedexams',
            name='full_mark',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
