# Generated by Django 2.2.3 on 2019-07-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20190701_1838'),
        ('exams', '0011_auto_20190705_1751'),
    ]

    operations = [
    ]
