# Generated by Django 2.2.3 on 2019-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_merge_20190705_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='full_mark',
        ),
        migrations.RemoveField(
            model_name='finishedexams',
            name='full_mark',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blank_avatar.png', upload_to='personal/%y/%m/'),
        ),
    ]
